### PR TITLE
README: add Root Access documentation page for Desktop

### PR DESCRIPTION
**Pull request by c-quenin**
Unrooted devices are now supported on some Desktop versions.
Add the corresponding documentation pages.

**JIRA**: [SYSTEM-1779](https://genymobile.atlassian.net/browse/SYSTEM-1779) and [SYSTEM-2475](https://genymobile.atlassian.net/browse/SYSTEM-2475)

[SYSTEM-1779]: https://genymobile.atlassian.net/browse/SYSTEM-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SYSTEM-2475]: https://genymobile.atlassian.net/browse/SYSTEM-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by c-quenin** [comment]
Added the `DO NOT MERGE` tag because we need to wait for the documentation to be released before merging this.

**Review by cmajed — APPROVED** [review]

**Review by gvercoutere-geny — APPROVED** [review]

**Review by jmaneyrol69 — APPROVED** [review]
LGTM. Just to let you know, @c-quenin , the doc PRs will be merged when the feature/product is released. I hope this won't delay the release?

**Comment by c-quenin** [comment]
Removing the DONOTMERGE tag as Desktop 3.7.0 has been released.
I've also removed the SaaS doc addition in another PR https://github.com/Genymobile/genymotion_platform_vendor_genymotion_security_public/pull/8 so that we can merge this one for Desktop and wait for the next SaaS release

**Review by gvercoutere-geny — APPROVED** [review]

**Review by jmaneyrol69 — APPROVED** [review]
LGTM

**Review by cmajed — APPROVED** [review]

**Pull request merged**
