### PR TITLE
[SYSTEM-1833][12.1] Declare supporting Android 12.1 signed builds

### PR DESCRIPTION
**Pull request by c-quenin**
JIRA: [SYSTEM-1833](https://genymobile.atlassian.net/browse/SYSTEM-1833)

[SYSTEM-1833]: https://genymobile.atlassian.net/browse/SYSTEM-1833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by c-quenin** [comment]
I've added the DO NOT MERGE tag, because this repository is public.
We don't want to merge this PR before releasing the corresponding PaaS versions to providers.
Also, we might want to specify in the README file from which PaaS version the 12.1 image is a signed user build.

**Comment by c-quenin** [comment]
@guillaume-roche I wonder if instead of specifying the supported versions in this repo we should add a link to a user doc from https://docs.genymotion.com/paas/? might be easier to maintain, to have one source where to get this info.

**Review by gvercoutere-geny — APPROVED** [review]

**Review by cmajed — APPROVED** [review]

**Comment by guillaume-roche** [comment]
> @guillaume-roche I wonder if instead of specifying the supported versions in this repo we should add a link to a user doc from https://docs.genymotion.com/paas/? might be easier to maintain, to have one source where to get this info.

Good idea!

**Comment by c-quenin** [comment]
> > @guillaume-roche I wonder if instead of specifying the supported versions in this repo we should add a link to a user doc from https://docs.genymotion.com/paas/? might be easier to maintain, to have one source where to get this info.
> 
> Good idea!

Ok, I've mentioned it in the user documentation ticket: https://genymobile.atlassian.net/browse/SYSTEM-2084, we'll update this PR accordingly

**Comment by c-quenin** [comment]
We must not update this repo before being able to release 12.1 user builds, we need to wait for the root/unroot feature for that. This repo update will be done in the context of https://genymobile.atlassian.net/browse/SYSTEM-2095

**Pull request closed without merging**
